### ISSUE TITLE
分享红包增加公众号二维码类型分享

### ISSUE THREAD

**Issue by JesseWeb** [JesseWeb/yxtg#16]

**Comment by jbRotk** [comment]
https://nei.netease.com/interface/detail/?pid=52017&id=290439

新增：
promote_share_url  推广公众号链接
customer_share_url  客户公众号链接

**Comment by JesseWeb** [comment]
![image](https://user-images.githubusercontent.com/23567445/79627141-6fc53b00-8168-11ea-93c1-424f51faa6b8.png)
