### ISSUE TITLE
推广动态需要新接口或新的参数，实现mt、elem都能获取

### ISSUE THREAD

**Issue by JesseWeb** [JesseWeb/yxtg#33]
### 现此处只有elem的：
![image](https://user-images.githubusercontent.com/23567445/79728537-a940a680-8320-11ea-8c3a-afe796374f38.png)

**Comment by jbRotk** [comment]
将type置为0或者不用带上type即可
![1587373887(1)](https://user-images.githubusercontent.com/17617719/79734957-1ad12280-832a-11ea-922f-5d7b937e5591.jpg)

**Comment by JesseWeb** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/23567445/79814243-544c7100-83b0-11ea-8e5e-a03a1a2d7a28.png">

**Comment by jbRotk** [comment]
已修复

**Comment by JesseWeb** [comment]
> 已修复

存在排序问题
