### ISSUE TITLE
授权流程优化

### ISSUE THREAD

**Issue by jbRotk** [JesseWeb/yxtg#34]
取消淘宝APP授权模式，授权界面替换为新图示界面，授权流程中取消返回按钮

旧
![1587604947_1_.jpg](https://i.loli.net/2020/04/23/FjkESZByT2AYJQf.png)
新
![a5fbf39d6af91af91784636b292ca1e.jpg](https://i.loli.net/2020/04/23/EnTHGZdvRlDXbcQ.jpg)

**Comment by JesseWeb** [comment]
取消app授权的理由是什么
