### ISSUE TITLE
首页新增我的直推返佣比例显示

### ISSUE THREAD

**Issue by jbRotk** [JesseWeb/yxtg#38]
![1587864834_1_.jpg](https://i.loli.net/2020/04/26/8NqIxljk6cuM4Oo.png)

点击提高返佣，跳转之前我的任务界面

**Comment by jbRotk** [comment]
https://nei.netease.com/interface/detail/res/?pid=52017&id=282500

直推比例字段 promote.rebate

**Comment by jbRotk** [comment]
UID:16275 改为邀请码  然后旁边加上一个复制邀请码的按钮

**Comment by JesseWeb** [comment]
建议UID改为ID，在其旁边加上复制邀请码按钮。

**Comment by JesseWeb** [comment]
done
