### ISSUE TITLE
提现界面入口带有结算的字眼均改为提现

### ISSUE THREAD

**Issue by jbRotk** [JesseWeb/yxtg#44]
![1589077703_1_.jpg](https://i.loli.net/2020/05/10/6WEXRYKfbvuxiBt.png)

**Comment by jbRotk** [comment]
![1589077703_1_.jpg](https://i.loli.net/2020/05/10/6WEXRYKfbvuxiBt.png)

**Comment by jbRotk** [comment]
![1589077703(1)](https://user-images.githubusercontent.com/17617719/81489548-36847480-92a9-11ea-96a9-e21f207cfe0e.jpg)

**Comment by JesseWeb** [comment]
done
